### ISSUE TITLE
Color Input Not working: undefined index id

### ISSUE THREAD

**Issue by InsaneSkull** [kartik-v/yii2-widget-colorinput#17]
When i use below line, 

    <?= $form->field($model, 'et_color_code')->widget(ColorInput::classname()) ?>

it says undefined index on 206 : 

      Html5InputAsset::register($view);
      $input = 'jQuery("#' . $this->html5Options['id'] . '")';    

**Note :-** Using Modal

**Comment by kartik-v** [comment]
Duplicate to  kartik-v/yii2-widgets#287. You need to ensure you have the latest updated release of `yii2-krajee-base`.
