### ISSUE TITLE
Fix demo page and update package to 1.0.3 with fixed #20

### ISSUE THREAD

**Issue by servocoder** [kartik-v/yii2-widget-colorinput#23]
Hello, I note that your colorinput widget demo page still have the bug desribed in https://github.com/kartik-v/yii2-widget-colorinput/issues/20, despite the bug was fixed. Check here: http://demos.krajee.com/widget-details/colorinput

I also expect you to update the package, so one will be able to checkout the fix via composer.
Thank you.

**Comment by kartik-v** [comment]
The demo pages are already updated long back with this issue.

It seems a classic issue of your client browser cache that is loading old assets - you may clear your browser cache and restart and try.
