### ISSUE TITLE
Demo Page Error

### ISSUE THREAD

**Issue by omer-sds** [kartik-v/yii2-widget-colorinput#29]
i was trying to check the documentation for pre-setting a color in the color picker but found that the demo page could not load colorpicker , please fix

**Comment by kartik-v** [comment]
The demos page seems to work ... [check advanced usage for color picker for example](http://demos.krajee.com/widget-details/colorinput#advanced-usage).

**Comment by winternet-studio** [comment]
@kartik-v On https://github.com/kartik-v/yii2-widget-colorinput you have the wrong link to the documentation - it has http://demos.krajee.com/widget-details/colorinputinput . So no one can find your documentation unless they happen to come here!
