### ISSUE TITLE
Color not properly computed when transparency set to 100%

### ISSUE THREAD

**Issue by Arnaud-G1** [kartik-v/yii2-widget-colorinput#3]
From your second example:

If transp = 0%
#000000 

If transp = 50%
rgba(0, 0, 0, 0.48)

If transp = 100%
#000000
while I would expect rgba(0, 0, 0, 1.0)

**Comment by kartik-v** [comment]
You may report this with the plugin author. BTW - the plugin has been updated to latest version - so you may want to retry this.
