### ISSUE TITLE
kartik\base\InputWidget and kartik\base\TranslationTrait define the same property ($i18n) in the composition of kartik\color\ColorInput. However, the definition differs and is considered incompatible. Class was composed

### ISSUE THREAD

**Issue by bmanop20** [kartik-v/yii2-widget-colorinput#36]
Hello,

I get this error:

kartik\base\InputWidget and kartik\base\TranslationTrait define the same property ($i18n) in the composition of kartik\color\ColorInput. However, the definition differs and is considered incompatible. Class was composed

Any hints how to get this problem solved?

Thanks

**Comment by kartik-v** [comment]
You have invalid outdated dependencies. Check your app's composer.json for any conflicting versions and ensure you do a proper `composer update` to get the latest release of `yii2-widget-colorinput` and `yii2-krajee-base`.
