### ISSUE TITLE
Input addon breaking layout

### ISSUE THREAD

**Issue by cpninformatica** [kartik-v/yii2-widget-colorinput#37]
After update the composer to:
**"kartik-v/yii2-widgets" : "3.4.0"** and **"kartik-v/yii2-krajee-base" : "1.9.9"**

The addon from color input plugin is breaking the layout (something with the spectrum css i guess).

**Example:**
![screenshot_2018-10-01 gercpn cadastrar banco](https://user-images.githubusercontent.com/37085179/46315430-ca596f00-c5a3-11e8-9310-e78ffbbe3785.png)

**Code:**
```
<div class="col-md-3 col-sm-3 col-lg-3 col-xs-12">
    <div class="form-group">
            <?= $form->field($model, 'cor')->widget(ColorInput::className(), [
                'showDefaultPalette' => true,
                'options' => ['placeholder' => 'Selecione uma cor ...'],
            ]);
        ?>
    </div>                
</div>
```

**Comment by kartik-v** [comment]
I assume you have bootstrap 3.x. [Cross check the demos](http://demosbs3.krajee.com/widget-details/colorinput) and see how you can render it better.

For bootstrap 4.x [cross check the demos](http://demos.krajee.com/widget-details/colorinput) and see how you can render it better.

**Comment by kartik-v** [comment]
I am not sure I can reproduce your issue - check your browser and client details and update.
This is what I can see on the [Bootstrap 3.x colorinput demos basic usage](http://demosbs3.krajee.com/widget-details/colorinput#basic-usage) on my browser.

![image](https://user-images.githubusercontent.com/3592619/46360646-82ad1300-c689-11e8-87bf-5385a0065d97.png)

[Bootstrap 3.x colorinput demos advanced usage](http://demosbs3.krajee.com/widget-details/colorinput#advanced -usage) on my browser.

![image](https://user-images.githubusercontent.com/3592619/46360810-d3bd0700-c689-11e8-89fb-18022339c010.png)

**Comment by darkdiesel** [comment]
The same issue. I found that you used 3.3.7 on your demo page. With last 3.4.1 i reproduced this bug.
