### ISSUE TITLE
The message file for category 'kvbase' does not exist

### ISSUE THREAD

**Issue by kasoft** [kartik-v/yii2-widget-colorinput#47]
I have a problem with the Message File, which is not found. Any idea what to fix?

The message file for category 'kvbase' does not exist: /usr/www/users/.../vendor/kartik-v/yii2-widget-colorinput/src/messages/de-DE/kvbase.php Fallback file does not exist as well: /usr/www/users/.../vendor/kartik-v/yii2-widget-colorinput/src/messages/de/kvbase.php

**Comment by kartik-v** [comment]
Ensure you have installed the kartik-v/yii2-widget packages via composer (and not manually copied files) to ensure you get all dependencies like kartik-v/yii2-krajee-base
